---
- name: check for a package.json file
  stat: path={{ source_dir }}/package.json
  register: package_json

- name: install gunicorn
  pip:
    name: gunicorn
    state: present
    version: "{{ gunicorn_version|default(omit) }}"
    virtualenv: "{{ venv_dir }}"
  become_user: "{{ project_user }}"

- name: configure gunicorn
  template: src=gunicorn.conf
            dest=/etc/supervisor/conf.d/{{ project_name }}-gunicorn.conf
            owner=root
            group=root
            mode=0600

- name: ensure gunicorn is present
  supervisorctl: name={{ project_name }}-server state=present

#- name: collectstatic
#django_manage: >
#command=collectstatic
#app_path={{ source_dir }}/{{ project_name }}
#virtualenv={{ venv_dir }}
#become_user: "{{ project_user }}"

- name: migrate
  django_manage: >
    command=migrate
    app_path={{ source_dir }}/{{ project_name }}
    virtualenv={{ venv_dir }}
  become_user: "{{ project_user }}"

- name: restart gunicorn
  supervisorctl: name={{ project_name }}-server state=restarted

- name: copy shell script wrapper for manage.py
  template: src=manage.sh
            dest={{ root_dir }}/manage.sh
            owner={{ project_name }}
            group={{ project_name }}
            mode=700
