---
- name: install gunicorn
  pip:
    name: gunicorn
    state: present
    version: "{{ gunicorn_version|default(omit) }}"
    virtualenv: "{{ venv_dir }}"
  become_user: "{{ project_user }}"

- name: ensure gunicorn is present
  supervisorctl: name={{ project_name }}-server state=present

- name: configure gunicorn
  template: src=gunicorn.conf
            dest=/etc/supervisor/conf.d/{{ project_name }}-gunicorn.conf
            owner=root
            group=root
            mode=0600
  tags:
    - deploy

- name: running Django collectstatic
  command: "./manage.sh collectstatic"
  become_user: "{{ project_user }}"
  args:
    chdir: "{{ root_dir }}"
  tags:
    - deploy

- name: running Django migrations
  command: "./manage.sh migrate"
  become_user: "{{ project_user }}"
  args:
    chdir: "{{ root_dir }}"
  tags:
    - deploy

- name: restart gunicorn
  supervisorctl: name={{ project_name }}-server state=restarted
  tags:
    - deploy
