- src: https://github.com/caktus/tequila-common
  version: v0.8.0
- src: https://github.com/caktus/tequila-django
  version: v0.8.0
- src: https://github.com/caktus/tequila-postgresql
  version: v0.8.0
- src: https://github.com/caktus/tequila-nginx
  version: v0.8.1
